CREATE TABLE saldosEstoque (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  emp VARCHAR(255) NULL,
  empresa VARCHAR(255) NULL,
  dep VARCHAR(255) NULL,
  deposito VARCHAR(255) NULL,
  nivel VARCHAR(255) NULL,
  grupo VARCHAR(255) NULL,
  sub VARCHAR(255) NULL,
  cor VARCHAR(255) NULL,
  produto VARCHAR(255) NULL,
  um VARCHAR(255) NULL,
  codigoBarras VARCHAR(255) NULL,
  codigoVelho VARCHAR(255) NULL,
  nomeGrupo VARCHAR(255) NULL,
  nomeSub VARCHAR(255) NULL,
  nomeCor VARCHAR(255) NULL,
  narrativa VARCHAR(255) NULL,
  cf VARCHAR(255) NULL,
  col VARCHAR(255) NULL,
  colecao VARCHAR(255) NULL,
  lin  VARCHAR(255) NULL,
  linha VARCHAR(255) NULL,
  art VARCHAR(255) NULL,
  artigo VARCHAR(255) NULL,
  cota VARCHAR(255) NULL,
  artigoCotas VARCHAR(255) NULL,
  ces VARCHAR(255) NULL,
  contaEstoque VARCHAR(255) NULL,
  tpg VARCHAR(255) NULL,
  tipoProdutoGlobal VARCHAR(255) NULL,
  tprogTpg VARCHAR(255) NULL,
  nivTpg VARCHAR(255) NULL,
  estTpg VARCHAR(255) NULL,
  depTpg VARCHAR(255) NULL,
  cliente VARCHAR(255) NULL,
  nomeCliente VARCHAR(255) NULL,
  marca VARCHAR(255) NULL,
  nomeMarca VARCHAR(255) NULL,
  tipoTecido VARCHAR(255) NULL,
  tpm VARCHAR(255) NULL,
  ncm VARCHAR(255) NULL,
  altp VARCHAR(255) NULL,
  rotp VARCHAR(255) NULL,
  antc VARCHAR(255) NULL,
  rotc VARCHAR(255) NULL,
  valorMedioEstoque DECIMAL(18,5) NULL,
  valorUltimaCompra DECIMAL(18,5) NULL,
  custo DECIMAL(18,5) NULL,
  custoInformado DECIMAL(18,5) NULL,
  lead VARCHAR(255) NULL,
  familiaTear VARCHAR(255) NULL,
  loteTam VARCHAR(255) NULL,
  pesoLiquido DECIMAL(18,5) NULL,
  pesoRolo DECIMAL(18,5) NULL,
  pesoMiniRolo VARCHAR(255) NULL,
  descTamFicha VARCHAR(255) NULL,
  tipoProdQuimico VARCHAR(255) NULL,
  itemAtivo VARCHAR(255) NULL,
  codigoContabil VARCHAR(255) NULL,
  codProcesso VARCHAR(255) NULL,
  lote VARCHAR(255) NULL,
  loteProduto VARCHAR(255) NULL,
  saldoAtual VARCHAR(255) NULL,
  volumes INTEGER NULL,
  qtEstqInicioMes VARCHAR(255) NULL,
  qtEstqFinalMes VARCHAR(255) NULL,
  ultimaEntrada TIMESTAMP NULL,
  ultimaSaida TIMESTAMP NULL,
  qtSugerida DECIMAL(18,5) NULL,
  qtEmpenhada DECIMAL(18,5) NULL,
  cnpjFornecedor VARCHAR(255) NULL,
  notaFiscal VARCHAR(255) NULL,
  periodoEstoque TIMESTAMP NULL,
  PRIMARY KEY(id)
);

CREATE PROCEDURE dbintegrafabric.uspSaldosEstoqueDeletar()
begin
	TRUNCATE TABLE saldosestoque;
END

-- Criando procedure uspSaldosEstoqueInserir
CREATE DEFINER=`abreu`@`%` PROCEDURE `dbintegrafabric`.`uspSaldosEstoqueInserir`(
	IN emp VARCHAR(255),
  IN empresa VARCHAR(255),
  IN dep VARCHAR(255),
  IN deposito VARCHAR(255),
  IN nivel VARCHAR(255),
  IN grupo VARCHAR(255),
  IN sub VARCHAR(255),
  IN cor VARCHAR(255),
  IN produto VARCHAR(255),
  IN um VARCHAR(255),
  IN codigoBarras VARCHAR(255),
  IN codigoVelho VARCHAR(255),
  IN nomeGrupo VARCHAR(255),
  IN nomeSub VARCHAR(255),
  IN nomeCor VARCHAR(255),
  IN narrativa VARCHAR(255),
  IN cf VARCHAR(255),
  IN col VARCHAR(255),
  IN colecao VARCHAR(255),
  IN lin  VARCHAR(255),
  IN linha VARCHAR(255),
  IN art VARCHAR(255),
  IN artigo VARCHAR(255),
  IN cota VARCHAR(255),
  IN artigoCotas VARCHAR(255),
  IN ces VARCHAR(255),
  IN contaEstoque VARCHAR(255),
  IN tpg VARCHAR(255),
  IN tipoProdutoGlobal VARCHAR(255),
  IN tprogTpg VARCHAR(255),
  IN nivTpg VARCHAR(255),
  IN estTpg VARCHAR(255),
  IN depTpg VARCHAR(255), 
  IN cliente VARCHAR(255),
  IN nomeCliente VARCHAR(255),
  IN marca VARCHAR(255),
  IN nomeMarca VARCHAR(255),
  IN tipoTecido VARCHAR(255),
  IN tpm VARCHAR(255),
  IN ncm VARCHAR(255),
  IN altp VARCHAR(255),
  IN rotp VARCHAR(255),
  IN antc VARCHAR(255),
  IN rotc VARCHAR(255),
  IN valorMedioEstoque DECIMAL(18,5),
  IN valorUltimaCompra DECIMAL(18,5),
  IN custo DECIMAL(18,5),
  IN custoInformado DECIMAL(18,5),
  IN lead VARCHAR(255),
  IN familiaTear VARCHAR(255),
  IN loteTam VARCHAR(255),
  IN pesoLiquido DECIMAL(18,5),
  IN pesoRolo DECIMAL(18,5),
  IN pesoMiniRolo DECIMAL(18,5),
  IN descTamFicha VARCHAR(255),
  IN tipoProdQuimico VARCHAR(255),
  IN itemAtivo VARCHAR(255),
  IN codigoContabil VARCHAR(255),
  IN codProcesso VARCHAR(255),
  IN lote VARCHAR(255),
  IN loteProduto VARCHAR(255),
  IN saldoAtual VARCHAR(255),
  IN volumes INTEGER,
  IN qtEstqInicioMes VARCHAR(255),
  IN qtEstqFinalMes VARCHAR(255),
  IN ultimaEntrada TIMESTAMP,
  IN ultimaSaida TIMESTAMP,
  IN qtSugerida DECIMAL(18,5),
  IN qtEmpenhada DECIMAL(18,5),
  IN cnpjFornecedor VARCHAR(255),
  IN notaFiscal VARCHAR(255),
  IN periodoEstoque TIMESTAMP
	
)
begin
	INSERT INTO saldosEstoque
	(
    emp,
    empresa,
    dep,
    deposito,
    nivel,
    grupo,
    sub,
    cor,
    produto,
    um,
    codigoBarras,
    codigoVelho,
    nomeGrupo,
    nomeSub,
    nomeCor,
    narrativa,
    cf,
    col,
    colecao,
    lin,
    linha,
    art,
    artigo,
    cota,
    artigoCotas,
    ces,
    contaEstoque,
    tpg,
    tipoProdutoGlobal,
    tprogTpg,
    nivTpg,
    estTpg,
    depTpg, 
    cliente,
    nomeCliente,
    marca,
    nomeMarca,
    tipoTecido,
    tpm,
    ncm,
    altp,
    rotp,
    antc,
    rotc,
    valorMedioEstoque,
    valorUltimaCompra,
    custo,
    custoinformado,
    lead,
    familiaTear,
    loteTam,
    pesoLiquido,
    pesoRolo,
    pesoMiniRolo,
    descTamFicha,
    tipoProdQuimico,
    itemAtivo,
    codigoContabil,
    codProcesso,
    lote,
    loteProduto,
    saldoAtual,
    volumes,
    qtEstqInicioMes,
    qtEstqFinalMes,
    ultimaEntrada,
    ultimaSaida,
    qtSugerida,
    qtEmpenhada,
    cnpjFornecedor,
    notaFiscal,
    periodoEstoque
	)
	VALUES 
	(
		emp,
    empresa,
    dep,
    deposito,
    nivel,
    grupo,
    sub,
    cor,
    produto,
    um,
    codigoBarras,
    codigoVelho,
    nomeGrupo,
    nomeSub,
    nomeCor,
    narrativa,
    cf,
    col,
    colecao,
    lin,
    linha,
    art,
    artigo,
    cota,
    artigoCotas,
    ces,
    contaEstoque,
    tpg,
    tipoProdutoGlobal,
    tprogTpg,
    nivTpg,
    estTpg,
    depTpg,
    cliente,
    nomeCliente,
    marca,
    nomeMarca,
    tipoTecido,
    tpm,
    ncm,
    altp,
    rotp,
    antc,
    rotc,
    valorMedioEstoque,
    valorUltimaCompra,
    custo,
    custoinformado,
    lead,
    familiaTear,
    loteTam,
    pesoLiquido,
    pesoRolo,
    pesoMiniRolo,
    descTamFicha,
    tipoProdQuimico,
    itemAtivo,
    codigoContabil,
    codProcesso,
    lote,
    loteProduto,
    saldoAtual,
    volumes,
    qtEstqInicioMes,
    qtEstqFinalMes,
    ultimaEntrada,
    ultimaSaida,
    qtSugerida,
    qtEmpenhada,
    cnpjFornecedor,
    notaFiscal,
    periodoEstoque
	);
END